xchem/XChemExplorer

gui_scripts/proasis_functions.py

https://github.com/xchem/XChemExplorer/issues/4

fixed proasis preventing load in wrong directory structure

---

XChemExplorer.py

Added functions from code that is used to update tables, as this worked as a manual solution.

fixed autoproc method selection changing main table

---

.travis.yml
Dockerfile
compile_test.py
run_tests
test_build.sh

The following things have been done:
- Created a docker container of ccp4 ([reskyner/ccp4](https://hub.docker.com/r/reskyner/ccp4/))
- Created a dockerfile for travis to build and run into ([reskyner/xce](https://github.com/reskyner/XChemExplorer/blob/master/Dockerfile))
- Created a travis yml file to build the xce file and run tests ([reskyner/XChemExplorer/.travis.yml](https://github.com/reskyner/XChemExplorer/blob/master/.travis.yml))
This should automatically build and run tests for whichever repository the commit has been done on (each dev might have to enable builds via Travis for their own repository)

Travis test template set up

---

lib/XChemLigand.py

- Needs latest version of RDKit
Fixes https://github.com/xchem/XChemExplorer/issues/23

Added RDKit supported way of doing Stereo Enumeration sensibly

---

Dockerfile
XChemExplorer.py

https://github.com/reskyner/XChemExplorer/commit/ceaa6758168e84e8425dbf91efc85963d10ed201

Solves pandda tab field text error

---

XChemExplorer.py
compile_test.py
lib/XChemMain.py
lib/XChemThread.py

https://github.com/xchem/XChemExplorer/issues/83
https://github.com/xchem/XChemExplorer/issues/57

A couple of issues fixed

---

XChemExplorer.py

https://github.com/xchem/XChemExplorer/issues/61

set default to acedrg

---

gui_scripts/pandda_tab.py
lib/XChemPANDDA.py

https://github.com/xchem/XChemExplorer/issues/64

https://github.com/xchem/XChemExplorer/issues/64 - done! :)

---

XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemCoot.py
lib/XChemCootNew.py
lib/XChemPANDDA.py
lib/XChemRefine.py

CCP4 is still interfering with COOT, but using the install script I wrote seems to solve it, for now...
I will make sure this is implemented in the VM.
To Do:
- unset LD_LIBRARY_PATH before remote submission within COOT interface, and reset afterwards
- get rid of some print statements that were used for testing
- deploy a version of the VM to Paddy and Alice for testing
- generate restraints remote submission

remote submission

---

XChemExplorer.py

Tobias sent this as a fix to the problem users are having with dimple not picking up the correct files from the datasource

dimple fix - Tobias

---

XChemExplorer.py
gui_scripts/datasets_tab.py
gui_scripts/settings_preferences.py
lib/XChemDB.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemThread.py

Major changes are:
pkl file is obsolete
results from every auto-processing pipeline are recorded in new DB table
results from fast_dp are NOT copied over anymore and are therefore not included in subsequent analyses
crystal centring images are copied into the project directory
beamline directory in project directory will not be used anymore!
INSTEAD: users need to actively select the actual data collection visit ("Data Collection Directory") in the settings tab; e.g. /dls/i04-1/data/2017/mx15433-50
if users want to select a different auto-processing outcome, they just need to click on the row of interest and a pop-up window with results from all pipelines will appear; a click on the desired outcome will change the results accordingly
internally, all the convoluted dictionaries which had …

Xce dev tk dc review

---

XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemProcess.py
lib/XChemThread.py
web/XChemWeb.py

- parsing of reprocessed files implemented
- XCE explicitly calls CCP4 version of xia2
- minor code cleanup
- declared v1.2

Xce dev tk 2018 06 18

---

gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemPANDDA.py
lib/XChemThread.py

- v1.2.1
- bug fix: dimple failed to run on csh on local machine due to DLS specific (bash) commands
- bug fix (not tested): pandda.analyse failed to run on local machine in tcsh shell; missing source command to obsolete pandda.setup file

Xce dev tk 2018 06 19

---

lib/XChemPANDDA.py

Still need to source ccp4, or the node doesn't know where to find the pandda.analyse command

added source ccp4 into pandda script

---

XChemExplorer.py
gui_scripts/pandda_tab.py

Options to select highlighted rows to:
- be ignored
- be excluded from characterisation
- be excluded from z-map analysis

Add select/deselect menu

---

XChemExplorer_dmd.sh
helpers/select_ground_state_dataset.py
lib/XChemRefine.py

This allows the phenix.quick_refine option to run in coot/refinement module. This has been tested with a small number of datasets. it should be used for further testing.
Racheal: The edit to XChemExplorer_dmd.sh was to keep to a recent branch change, please set this to whatever is appropriate. Shout if you need me to make the change.
Thanks
Elliot

Pandda phenix

---

XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemCootNew.py
lib/XChemDB.py
lib/XChemDeposit.py
lib/XChemPANDDA.py
lib/XChemRefine.py
lib/XChemThread.py
lib/XChemUtils.py
web/XChemWeb.py

- changed version to v1.3
- bug fix: get space group from aimless log file if file contains output from other programs like unique
- bug fix: change qsub command for dimple and restraints generation so that it works outside DLS
- new feature: assign labels to datasets in xce-coot interface
- bug fix: accomodate None value when querying DB for event map information
- new feature: preparation of apo mmcif files containing SF's all all datasets used for pandda.analyse
- improvement: refinement of pandda models enabled where ligand binding did not lead to any differences between bound-state and ground-state
- bug fix: update data_rxxxxsf field in apo mmcif file

Xce dev tk 2018 11 19

---

gui_scripts/settings_preferences.py
lib/XChemCootNew.py
lib/XChemLog.py
lib/XChemThread.py
lib/XChemUtils.py

changed version number to v1.3.1 and date to 25/01/2019
bug fix: support of new autoProc directory structure at DLS
bug fix: removal of non-existent DataProcessingProgram entries at DLS from collectionTable
bug fix: xce coot plugin: changed layout so that full window can be displayed on any screen

Xce dev tk 2019 01 25

---

gui_scripts/settings_preferences.py
lib/XChemCootNew.py
lib/XChemLog.py

* changed version number to v1.3.2 and date to 12/02/2019
* bug fix: removed reference to non-existent labels (prevented opening of pandda models/ maps)

Xce dev tk 2019 01 28

---

XChemExplorer.py
gui_scripts/deposition_tab.py
gui_scripts/settings_preferences.py
lib/XChemCoot.py
lib/XChemCootNew.py
lib/XChemDB.py
lib/XChemDeposit.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemRefine.py
lib/XChemThread.py
lib/XChemToolTips.py
lib/XChemUtils.py

v1.3.8 (25/04/2019) 
- added possibility to deposit protein-protein complex structure
- XChemDeposit - create table_1 from final mmcif file
- XChemDeposit - add option to not include event maps in SF mmcif file
- bug fix: XChemDeposit - use beamline information from mainTable 
v1.3.7 (18/03/2019) 
- implemented pop-up window to remind users where they started xce - minor change
v1.3.6 (14/03/2019)
- new deposition tab with step-by-step instructions regarding PanDDA group depositions
- some obsolete commands were removed from menu and action boxes
- added instructions about how to update DB with PDB codes after group deposition of ligand bound structures
- bug fix: add only structures which are '5-ready for deposition' to tar archive for PDB upload
- increment existing .tar.bz2 files in …

Xce dev tk 2019 02 19

---

gui_scripts/settings_preferences.py
lib/XChemCootNew.py
lib/XChemDB.py
lib/XChemPANDDA.py
lib/XChemThread.py

v1.3.8.2 (17/05/2019) 
- bug fix: avoid overwriting of ligand confidence when updating DN from file system: removed option to 'Update datasource with results from pandda.inspect' + changed XChemPanDDA that only the panddaTable gets only updated for models that ought to be exportet.
- bug fix (temporary): removed label option because it does not behave as expected
- XChemDB: removed PANDDA_site_ligand_placed constraint from query for pandda models

Xce dev tk 2019 05 17 ii

---

gui_scripts/settings_preferences.py
lib/XChemCoot.py
lib/XChemCootNew.py
lib/XChemDB.py
lib/XChemLog.py
lib/XChemRefine.py

v1.3.8.3 (22/05/2019) 
- XChemCOOT: xce-coot messages are now written to xce.log file (not all, yet)
- XChemCOOT: warning message added in case cootOut/Refine_<n> folder exists
- bug fix: XChemDB: remove hidden characters like \r and \n when updating depositTable
- XChemDB: changed single to double quotation marks (and vice versa) in update depositTable function to allow for example 5' in structure title

Xce dev tk 2019 05 21

---

gui_scripts/settings_preferences.py
lib/XChemCoot.py
lib/XChemLog.py
lib/XChemUtils.py

v1.3.8.6 (31/05/2019) 
- XChemCOOT-test: added menu funciton to set occupancy of all protein residues to 1 (IMPORTANT: requires COOT v0.8.9.2 or higher)

v1.3.8.6 (31/05/2019) 

---

gui_scripts/settings_preferences.py
lib/XChemLog.py

v1.3.8.7 (06/06/2019) 
- 'model_building' is now the new default initial_model directory

Xce dev tk 2019 06 06

---

XChemExplorer.py
gui_scripts/settings_preferences.py
gui_scripts/settings_tab.py
lib/XChemDB.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemThread.py
lib/XChemUtils.py

v1.3.8.9 (07/08/2019) 
- added option to parse Agamemnon data structure at DLS
- removed obsolete 'Run DIMPLE on All Autoprocessing MTZ files' option from yellow Datasets action box

Xce dev tk 2019 08 06

---

gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemThread.py

- added few changes to enable parsing of DLS visit directories transfered to other file system

v1.3.8.11 (04/09/2019)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemThread.py
lib/XChemToolTips.py

v1.3.8.12 (10/09/2019)
- new task for merging CIF file of non-standard ligand with compoound CIF files
- added exception to catch IOError during opening of gzipped gda logfile

v1.3.8.12 (10/09/2019)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemThread.py

changes to parsing of auto-collected visits ("agamemnon") due to DLS changes to folder structure (now called 'auto' instead of 'agamemnon')

v1.3.8.13 (27/09/2019)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py

- bug fix: added except statement in get_gda_barcodes to catch errors during parsing of multiple visits

v1.3.8.18 (25/11/2019) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py

- introduced simple semantic versioning according to https://semver.org

v1.4.0 (03/12/2019) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemRefine.py

- bug fix: arbitrary clicking order for atoms making a new covalent link

v1.4.2 (17/12/2019)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemPANDDA.py

- added additional error message during pandda.export in case of missing ensemble model

v1.4.3 (10/10/2019)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemPANDDA.py

- bug fix: corrected pandda.analyse keyword 'exclude_from_z_map_analysis'

v1.4.4 (10/01/2019)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemThread.py

- bug fix: removing and re-parsing of folders from project directory does not need the DataProcessingAutoAssigned flag to be reset if the MTZ file does not exist

v1.4.5 (16/01/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
helpers/change_residues_in_ground_and_bound-state.py
lib/XChemLog.py

- added script to helpers which can replace residues in bound and ground state based on a new reference model (change_residues_in_ground_and_bound-state.py); cannot be called from GUI at the moment

v1.4.7 (07/02/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemThread.py

- bug fix: correct determination of staraniso runs for different space groups

v1.5.2 (25/02/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemThread.py

- bug fix: iotbx spg symbol for H32 needed changing for unique step of initial map calculation

v1.5.4 (27/02/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemPANDDA.py

- bug fix: update depositTable with ground_state_sf.mmcif if successfully created

v1.5.5 (27/02/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py

- added Taxonomy ID for BAT SARS-LIKE CORONAVIRUS and COVID-19

v1.5.6 (02/03/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
web/XChemWeb.py

- bug fix: capture all available event maps during html export

v1.5.7 (03/03/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py

- added Taxonomy ID for mus musculus

v1.5.8 (04/03/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemThread.py

- bug fix: reading of .json scaling logfiles enabled during 'update database from filesystem

v1.5.9 (05/03/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
web/XChemWeb.py

- bug fix: correct name of event map in files directory

v1.5.10 (05/03/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemThread.py

- DIMPLE: added pointless step before dimple to reindex according to ref_pdb if necessary

v1.5.12 (10/03/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemPANDDA.py

- bug fix: include covlinks argument is None in XChemPANDDA quickRefine

v1.5.13 (11/03/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py
web/XChemWeb.py

- HTML export: enable changing of contour level of event maps
- HTML export: set ligand confidence to "not assigned" for deposition ready model that have "0 - no ligand bound"

v1.5.14 (14/03/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemPANDDA.py

- bug fix: found instance in pandda_inspect_events.csv where sites/ events displayed as float instead of int; added fix

v1.5.15 (06/04/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemLog.py

- added option to specify $SampleID in structure deposition title

v1.5.17 (07/04/2020) 

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemCootBuster.py
lib/XChemLog.py
lib/XChemPANDDA.py
lib/XChemRefine.py
lib/XChemThread.py

- new option: directly refine bound-state only after pandda.inspect with buster

v1.6.0 (14/04/2020)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemDB.py
lib/XChemLog.py

- added '7 - Analysed & Rejected' to refinement table combobox

v1.6.1 (17/04/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemThread.py
lib/XChemUtils.py

- restraints generation: use program name in script name for easier trouble-shooting
- assign_stereochemistry.py option removed from restraints generation

v1.6.2 (24/04/2020)

---

ChangeLog.txt
XChemExplorer_dmd.sh
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemUtils.py

- grade will use mogul for restraints generation if program available 

v1.6.3 (25/04/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemRefine.py

- added validation with buster-reports after refinement with buster

v1.6.4 (28/04/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemRefine.py

- more verbose error messages in buster refine module

v1.6.5 (28/04/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemRefine.py

- bug fix: NameError in XChemRefine

v1.6.6 (28/04/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
helpers/update_data_source_for_new_dimple_twin_pdb.py
lib/XChemDB.py
lib/XChemLog.py
lib/XChemThread.py
lib/XChemUtils.py

- initial twin refinement with dimple in separate folder and additional fields in XChemDB

v1.6.7 (29/04/2020)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemDB.py
lib/XChemLog.py
web/XChemWeb.py

- enable html export of '4 - CompChem ready' structures only

v1.6.8 (30/04/2020) 

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemCootTwin.py
lib/XChemLog.py
lib/XChemThread.py

- added COOT command to open dimple_twin maps

v1.6.9 (04/05/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
helpers/update_data_source_after_refinement.py
lib/XChemDB.py
lib/XChemRefine.py

- added giant.score_model after buster refinement
- added field and capture of path to buster-reports in DB

v1.6.11 (04/05/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
helpers/update_data_source_after_refinement.py
lib/XChemDB.py
lib/XChemLog.py

- capture refinement mmcif file location in DB after refinement (if available)

v1.6.12 (09/05/2020) 

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemDB.py
lib/XChemLog.py
web/XChemWeb.py

- added html summary for all '5-deposition ready' structures 
- HTML summary: show NO_SPIDER_PLOT_AVAILABLE.png if spider plot is missing

v1.6.15 (12/05/2020) 

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemPANDDA.py

- XChemExplorer.py removed unused 'import gtk' statement which is incompatible with ccp4 7.1

v1.6.16 (12/05/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemPANDDA.py

- removed dls specific source files from pandda analyse script when running on local machine

v1.6.18 (17/05/2020) 

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemThread.py

- combined parsing of 'agamemnon' auto-collection into single function

v1.6.19 (28/05/2020)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemRefine.py

- enable remote cluster submission of (Buster) refinement jobs

v1.6.20 (03/06/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemRefine.py

- source ccp4 7.0 at Diamond before running giant.score_model during Buster refinement

v1.6.21 (04/06/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemRefine.py

- added mapmask step after map calculation in buster refinement in order to cover entire molecule (required for nglview)

v1.6.22 (11/06/2020)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemPANDDA.py
lib/XChemUtils.py

- use gemmi (if available) to convert event maps to mtz

v1.6.23 (12/06/2020)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemThread.py

- backup soakDB after restart and 'update database from filesystem'

v1.6.25 (22/06/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemCootBuster.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemRefine.py

- added option for anisotropic B-factor refinement with Buster

v1.6.26 (24/06/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemCootBuster.py
lib/XChemLog.py
lib/XChemRefine.py

- made water update optional when refining with with Buster

v1.6.27 (28/06/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
helpers/update_data_source_after_refinement.py
lib/XChemDB.py
lib/XChemRefine.py

- added capture of refiner and date of refinement in DB after refinement

v1.6.28 (28/06/2020)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemCootBuster.py
lib/XChemCootNew.py
lib/XChemDB.py

- added capture of person (and date) changing RefinementOutcome field in DB

v1.6.29 (28/06/2020)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py

- select auto-refinement from action box not from preferences

v1.7.1 (13/07/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py
lib/XChemThread.py

- bug fix: selected results not linked after parsing of auto-processing results
- enabled updates of message & progress bar during scoring of auto-processing results
- enabled updates of message & progress bar during DB update of pinIDs

v1.7.4 (21/07/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemUtils.py

- bug fix: logical error in creation of restraints script when adding 'module load ccp4/phenix' command
- removed phenix.reduce step from restraints generation

v1.7.7 (22/07/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemCootNew.py
lib/XChemLog.py
lib/XChemThread.py

- bug fix: string formatting error during restraints generation on local machine
- added scanchirals option to rhofit command in fit_ligands function
- bug fix: added 'module load buster' to fit_ligands function

v1.7.8 (01/09/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemLog.py

- bug fix: preparation of mmcif files: run aimless in onlymerge mode if only json file available

v1.7.11 (09/09/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemLog.py

- bug fix: problem with recognizing AIMLESS logfiles during preparation of MMCIF files
- bug fix: try finding experimental wavelength from .free.mtz file if it is 0.0 in refine.mtz during MMCIF file preparation
- preparation of mmcif files: catch and report missing event mtz files

v1.7.12 (14/09/2020)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemPANDDA.py
lib/XChemRefine.py

- added option to ignore GELLY sanity check in BUSTER
- added option to ignore GELLY sanity check during pandda export with BUSTER

v1.7.15 (25/09/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemPANDDA.py

- bug fix: corrected positions of ignore checkboxes in pandda.analyse

v1.7.17 (09/10/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemRefine.py

- bug fix: remove undocumented and faulty changes to RunQuickRefine

v1.7.20 (16/10/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py

- capitalized organism names in NCBI_taxonomy_ID dictionary

v1.7.24 (02/11/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemLog.py
lib/XChemUtils.py

- convert json logfile from dials into pseudo aimless file for mmcif file preparation (required for pdb-extract)

v1.7.25 (11/11/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemLog.py

- XChemDeposit: remove \n and \r from smiles string in _diffrn.details

v1.7.26 (12/11/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDB.py
lib/XChemLog.py

- bug fix: add missing DataProcessingUniqueReflectionsLow/High column to db

v1.7.27 (24/11/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemMain.py

- added exception to catch 'Cannot allocate memory' error in XChemMain.get_gda_barcodes

v1.7.28 (25/11/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemLog.py

- bug fix: syntax error in XChemDeposit
- XChemDeposit: use default pdb_extract if no installation in XChemExplorer_dir

v1.7.29 (09/12/2020)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemLog.py

v1.7.30 (17/12/2020) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemLog.py

- bug fix: XChemDeposit - enable reading of staraniso .table1 file

v1.7.31 (20/01/2021)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemDeposit.py
lib/XChemLog.py

- bug fix: XChemDeposit - enable reading of not symlinked logfiles

v1.7.32 (24/01/2021) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemCootBuster.py
lib/XChemCootNew.py
lib/XChemLog.py

- bug fix: enable RefinementParameters button in XChemCOOT

v1.7.33 (02/02/2021) 

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemThread.py

- ignore json merging statistics and xia2.mmcif if aimless.log exists

v1.7.35 (13/10/2021)

---

ChangeLog.txt
XChemExplorer.py
gui_scripts/pandda_tab.py
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemPANDDA.py

- add functionality for running PanDDA2 at Diamond Light Source
- fixed hyperlink to PanDDA manual

v1.9.0 (22/04/2022)

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemUtils.py

- added 'module load ccp4/7.1.018' to grade script otherwise the helper script will run with python3

v1.9.3 (29/06/2022) 

---

ChangeLog.txt
gui_scripts/settings_preferences.py
lib/XChemLog.py
lib/XChemUtils.py

- catch unusual space group names in PDB CRYST card

v1.9.4 (10/10/2022) 

---

xce/lib/XChemPANDDA.py

A quick hotfix to handle when these fields are empty

A quick fix for when these parameters are empty
