xchem/XChemExplorer

- gui_scripts/proasis_functions.py
Originally, the user account that XCE was run from would try to write to the proasis directories, and get a permission denied, as the user doesn't have access to /dls/science/groups/proasis. To solve this, the user now writes a temporary .sh file called proasis_tmp.sh in the processing directory, containing all of the commands necessary to copy files to the right place, and to add jobs to the proasis queue. Then, proasis searches the /dls/labxchem/data directory for any proasis_tmp.sh files in a processing directory, runs them, and then removes the file.
> Changed how XCE/proasis is integrated

- gui_scripts/settings_preferences.py
- helpers/update_data_source_for_new_dimple_pdb.py
- lib/XChemCoot.py
- lib/XChemDeposit.py
- lib/XChemLog.py
- lib/XChemPANDDA.py
- lib/XChemThread.py
v1.3.8.4 (23/05/2019) 
- bug fix: new initial refinement mechanism does not use the dimple_rerun_on_selected_file subfolder which meant that the .free.mtz file was not selected after the run
- XChemPanDDA export: changed how models will be selected for refinement
- XChemPanDDA export: removed update of obsolete DimplePANDDAhit field in database
- XChemPanDDA export: removed false alarm during export #217
- XChemDeposit: added check for .free.mtz file
- XChemCOOT: add XCE menu (test version only)
- XChemCOOT: add menue item to set occupancy of all protein residues to 1.0 (test version only)
> Xce dev tk 2019 05 22

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemCootReference.py
- lib/XChemLog.py
- bug fix: refine routine in XChemCootReference.py did not contain argument for covalent bonds
> v1.3.8.17 (20/11/2019) 

- ChangeLog.txt
- XChemExplorer.py
- gui_scripts/settings_preferences.py
- lib/XChemDB.py
- lib/XChemLog.py
- lib/XChemThread.py
- lib/XChemUtils.py
- bug fix: xce to read resolution at Mn(I)/sig(I) of 2.0 (and 1.5 if possible) from aimless log; now only reads either one or the other. Datasets table now only shows reso at 2.0 since 1.5 not always shown
- bug fix: read gda barcodes into DB and display in datasets table
> v1.3.8.19 (02/12/2019)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- helpers/assign_stereochemistry.py
- lib/XChemLog.py
- lib/XChemThread.py
- lib/XChemUtils.py
- bug fix: in helpers/assign_stereochemistry.py; use CompoundSMILES instead of CompoundSMILESproduct (which need to be provided by user)
- bug fix: auto-fitting of ligands - use default ccp4 distribition and submission command
- bug fix: add 'module load mx' to restraints generation script; uses default ccp4 installation, otherwise CLIB path for GRADE broken
> v1.4.1 (16/12/2019)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- bug fix: default labxchem folders are only selected if xce starts in /dls/labxchem/...; just having labxchem in current directory string is not sufficient
> v1.4.8 (07/02/2020)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- lib/XChemUtils.py
- bug fix: corrected DataProcessingUnitCellVolume calculation from merging-statistics.json file for trigonal lattice
- show only 'resolution high' in tables because formatting for resolution at 1.5 or 2.0 I/sig(I) inconsistent in aimless logfiles and not reported in dials scaling logile
> v1.4.9 (13/02/2020)

- ChangeLog.txt
- XChemExplorer.py
- gui_scripts/deposition_tab.py
- gui_scripts/settings_preferences.py
- lib/XChemDB.py
- lib/XChemDeposit.py
- lib/XChemLog.py
- lib/XChemToolTips.py
- lib/XChemUtils.py
- ground-state mean maps are EXCLUDED from apo deposition, because either map2mtz conversion was faulty or columns were missing; moreover, they are not required to reproduce the maps and users can deposit them separately on ZENODO if they want
> v1.5.0 (20/02/2020)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- lib/XChemUtils.py
- bug fix: read spacegroup as H32 from xia2.mmcif ('R 3 2 :H')
> v1.5.3 (26/02/2020) 

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemDB.py
- lib/XChemMain.py
- lib/XChemThread.py
- XChemThread: copy un-merged MTZ file for xia2, dials & 3d(ii)
- XChemThread: change parsing of auto-processing results to enable reading of multiple runs with same name, e.g. xia-3dii
- bug fix: enable 3dii only selection of auto-processing results
- remove xia2-3d only auto-processing selection option
> v1.5.16 (06/04/2020)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemCootTwin.py
- bug fix: only read (2)fofc_twin.map during dimple_twin map review
> v1.6.10 (04/05/2020) 

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemDeposit.py
- lib/XChemLog.py
- XChemDeposit: use RefinementMMCIFmodel_latest (if available) instead of refine.split.bound-state.pdb
> v1.6.13 (10/05/2020) 

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemDeposit.py
- lib/XChemLog.py
- lib/XChemUtils.py
- XChemUtils: get BUSTER from PROGRAM REMARK
- XChemDeposit: usage of model mmcif file disabled because of unclear errors during group deposition
- XChemDeposit: do not add ligand cif to model mmcif because Buster does already include it
- XChemDeposit: use pdb_extract v3.26 when using mmcif instead of pdb files
> v1.6.14 (11/05/2020)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- lib/XChemThread.py
- DIMPLE: added 'tolerance 5' keyword to pointless step to allow reindexing in case of slightly larger unit cell differences
> v1.6.17 (17/05/2020) 

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- lib/XChemRefine.py
- bug fix: missing '\n' in calculate_maps (XChemRefine) deleted soakDB file
> v1.6.24 (22/06/2020)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemUtils.py
- bug fix: remove obsolete 'module load mx' statement from xce_<restraints_prg> script which currently loads a gemmi incompatible ccp4 version
> v1.7.5 (21/07/2020)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- lib/XChemUtils.py
- bug fix: added 'module load ccp4/phenix' to restraints script in case not part of user bashrc file
> v1.7.6 (22/07/2020) 

- ChangeLog.txt
- XChemExplorer.py
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- change 'Open COOT' to 'Open COOT - REFMAC refinement -' in Refinement action box
> v1.7.9 (03/09/2020) 

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemDeposit.py
- lib/XChemLog.py
- bug fix - preparation of mmcif files for deposition: enable usage of event mtz files which were generated during 'BUSTER' export routine
> v1.7.10 (08/09/2020)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemDeposit.py
- lib/XChemLog.py
- bug fix: use wavelength read from (.free).mtz during model MMCIF preparation when updating SF MMCIF
> v1.7.13 (23/09/2020) 

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemCootBuster.py
- lib/XChemLog.py
- lib/XChemRefine.py
- added option for ligand occupancy refinement in BUSTER
- XChemCootBuster: reading of (2)fofc.maps disabled because Coot 0.9 does not handle P1 maps well
> v1.7.14 (24/09/2020)

- ChangeLog.txt
- XChemExplorer.py
- gui_scripts/settings_preferences.py
- helpers/reset_to_last_successful_refinement.py
- lib/XChemCootBuster.py
- lib/XChemCootNew.py
- lib/XChemDB.py
- lib/XChemLog.py
- lib/XChemPANDDA.py
- lib/XChemRefine.py
- enable export of selected datasets with pandda.export
- glitch fix: remove hydrogens before saving model for buster refinement (causes problems during ligand occupancy refinement)
- XChemRefine: removed "-q medium.q" option for non-DLS refinement
- added helper script to which reverts to last successful non-pandda refinement
- XChemCoot (pandda refinement): reading of (2)fofc.maps disabled because Coot 0.9 does not handle P1 maps well
- pandda.analyse: stopped sourcing obsolete pandda v0.2.12 at DLS
> v1.7.16 (08/10/2020)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- lib/XChemPANDDA.py
- bug fix: added missing 'module load ccp4' statement when generating pandda.analyse shell script at DLS
> v1.7.18 (12/10/2020) 

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemPANDDA.py
- bug fix: use 'module load ccp4/7.0.072' for pandda.analyse, but 'module load ccp4' (i.e. v7.1) for pre-run ground-state selection at DLS
> v1.7.19 (12/10/2020) 

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- lib/XChemRefine.py
- bug fix: use default CCP4 for giant.merge_conformations
> v1.7.21 (19/10/2020)

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- lib/XChemRefine.py
- pandda refinement: stopped sourcing obsolete pandda v0.2.12 at DLS (otherwise refinement update script fails due to missing gemmi library)
> v1.7.23 (02/11/2020) 

- ChangeLog.txt
- gui_scripts/settings_preferences.py
- lib/XChemLog.py
- lib/XChemPANDDA.py
replace obsolete 'source /dls/science/groups/i04-1/software/pandda-update/ccp4/ccp4-7.0/bin/ccp4.setup-sh' with 'module load ccp4/7.1.016' before running pandda.export
> v1.9.2 (28/06/2022)  

- XChemExplorer_dls
- xce/lib/XChemRefine.py
- xce/lib/XChemUtils.py
it is likely that the existing mogul path `BDG_TOOL_MOGUL="/dls_sw/apps/ccdc/CSD_2020/bin/mogul` would be affected by the `module load ccdc` deprecation warning.
path updated to latest: `/dls_sw/apps/CSDS/2024.1.0/ccdc-software/mogul/bin/mogul`
> update mogul path to CSDS 2024

- xce/lib/XChemRefine.py
Increased `tasks` in `slurm.submit_cluster_job` for buster and refmac refinement jobs.  
Given that buster refine appears to use max 8 cores ([https://www.globalphasing.com/buster/manual/autobuster/manual/autoBUSTER4.html#:~:text=By%20default%2C%20the%20%22refine%22,refine%20argument%20%2Dnthreads%20is%20used](https://www.globalphasing.com/buster/manual/autobuster/manual/autoBUSTER4.html#:~:text=By%20default%2C%20the%20%22refine%22,refine%20argument%20%2Dnthreads%20is%20used)) requesting exclusive node access on these jobs would seem to be inefficient, so have opted for 8 cores for these jobs.
> set buster refmac tasks

- xce/lib/XChemRefine.py
`buster-report` has been failing due to the absence of graphviz libraries on the cluster nodes. These libraries have now been installed by scientific computing and can be accessed with `module load graphviz`. This command has been added to the preamble before `buster-report` is executed in xce.
I have tested `buster-report` on the cluster with some test data and the expected output files (report.pdf, index.html etc) are now successfully produced.
> Get buster-report working again
